# Changes here will be overwritten by Copier
_commit: v0.1.7
_src_path: gh:edgarrmondragon/singer-tap-copier-template
author_email: edgarrm358@gmail.com
author_fullname: Edgar Ramírez-Mondragón
author_username: edgarrmondragon
dependabot_update_time: '10:00'
dependabot_update_timezone: Etc/UTC
python_main_version: '3.13'
repository_name: tap-eventbrite
repository_namespace: reservoir-data
repository_provider: github.com
repository_visibility: public
tap_auth_method: Bearer Token
tap_id: tap-eventbrite
tap_package_command_line_name: tap-eventbrite
tap_package_distribution_name: tap-eventbrite
tap_package_import_name: tap_eventbrite
tap_source_description: Global self-service ticketing platform for live experiences
tap_source_id: Eventbrite
tap_source_name: Eventbrite
tap_stream_type: REST
vscode_files: true
